weather/importapi/urls.py
from django.urls import path

from . import views

app_name='importapi'
urlpatterns = [
    path('', views.importdataapi, name='importdataapi')
]

weather/weather/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, path
from rest_framework import routers
from restapi import views

router = routers.DefaultRouter()
router.register(r'city', views.CityViewSet)
router.register(r'weather', views.WeatherViewSet)


urlpatterns = [
    path('', include('weather_stats.urls'), name='indexx'),
    path('api/',include(router.urls)),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('import/', include('importapi.urls'))
]

weather/weather_stats/urls.py
from django.urls import path

from . import views

app_name='weather_stats'
urlpatterns = [
    path('', views.index, name='index'),
    path("<int:cityid>", views.miasto, name="miasto"),
    path("del/<int:cityid>", views.delmiasto, name="delmiasto")
]

weather/importapi/models.py
from django.db import models

# Create your models here.

weather/restapi/models.py
from django.db import models

# Create your models here.

weather/weather_stats/models.py
from django.db import models

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=254)
    cityid = models.IntegerField()
    coordlon = models.FloatField()
    coordlat = models.FloatField()

    def __str__(self):
        return f"{self.name}"

class Weather(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    date = models.DateTimeField()
    temp = models.FloatField()
    temp_min = models.FloatField()
    temp_max = models.FloatField()
    temp_feels = models.FloatField()
    pressure = models.FloatField()
    weather_main = models.CharField(max_length=32)
    weather_desc = models.CharField(max_length=64)
    weather_icon = models.CharField(max_length=32)

weather/importapi/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
import requests
from weather_stats.models import City, Weather
# Create your views here.
def sendRequest(request, miasto):
    link="https://api.openweathermap.org/data/2.5/forecast?appid=50e6d49e940dd59765f1a0a6f19e7e4b&units=metric&lang=pl&q="
    link += miasto
    res = requests.get(link)
    data = res.json()
    return data

def importdataapi(request):
    miasto = request.POST.get('wpisane_miasto')
    data = sendRequest(request, miasto)
    if data['cod'] != "200":
        return redirect('/', foo='bar')
    cityapi = data['city']
    weatherlist = data['list']
    cityajdi = cityapi['id']
    try:
        city = City.objects.get(cityid=cityajdi)
    except City.DoesNotExist:
        a = City()
        a.cityid = cityapi['id']
        a.name = cityapi['name']
        a.coordlat = cityapi['coord']['lat']
        a.coordlon = cityapi['coord']['lon']
        a.save()
        city = City.objects.get(cityid=cityajdi)
    finally:
        Weather.objects.filter(city=city).delete()
        for w in weatherlist:
            b = Weather()
            b.city = City.objects.get(cityid=cityajdi)
            b.date = w['dt_txt']
            b.temp = w['main']['temp']
            b.temp_min = w['main']['temp_min']
            b.temp_max = w['main']['temp_max']
            b.temp_feels = w['main']['feels_like']
            b.pressure = w['main']['pressure']
            b.weather_main = w['weather'][0]['main']
            b.weather_desc = w['weather'][0]['description']
            b.weather_icon =w['weather'][0]['icon']
            b.save()
    return redirect('/', foo='bar')

weather/restapi/views.py
from rest_framework import viewsets, filters
from restapi.serializers import CitySerializer, WeatherSerializer
from weather_stats.models import City, Weather

class CityViewSet(viewsets.ModelViewSet):
    queryset = City.objects.all()
    serializer_class = CitySerializer

class WeatherViewSet(viewsets.ModelViewSet):
    queryset = Weather.objects.all()
    serializer_class = WeatherSerializer
    search_fields = ['city__name']
    filter_backends = (filters.SearchFilter,)

weather/weather_stats/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import City, Weather
from django.db.models import Avg, Count, Max
import json 
from django.core.serializers.json import DjangoJSONEncoder
import requests
# Create your views here.

def index(request):
    miasta = City.objects.all()
    data = {
        'City' : miasta
    }
    return render(request, 'weather_stats/index.html', data)

def miasto(request, cityid):
    try:
        city = City.objects.get(pk=cityid)
        args = Weather.objects.filter(city__in=City.objects.filter(name=city.name))
        weather = args.distinct()
        srednia = args.aggregate(Avg('temp'), Max('temp'))
        arg = args.order_by('-temp').first()
        popularnosc = args.values_list('weather_desc').annotate(truck_count=Count('weather_desc')).order_by('-truck_count').first()

    except City.DoesNotExist:
        raise Http404("Brak miasta w bazie")
    data = {
        "city": city,
        "weather": weather,
        "srednia": srednia,
        "popularnosc": popularnosc,
        "najcieplejszy" : arg
    }
    return render(request, "weather_stats/miasto.html", data)

def delmiasto(request, cityid):
    City.objects.filter(pk=cityid).delete()
    return redirect('/', foo='bar')

weather/weather_stats/templates/weather_stats/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'weather_stats/styles.css' %}"/>
    </head>
    <body>
        <div class="box">
         <div class="wrapper">
        {% block body %}
        {% endblock %}    
        </div>   
        </div>
        
    </body>
</html>

weather/weather_stats/templates/weather_stats/index.html
{% extends "weather_stats/base.html" %}

{% block title %}
    Miasta
{% endblock %}
{% block body %}
    <h1>Miasta</h1>

    {% for post in City %}
        <li>
            <a href="{{post.id}}">
                {{post.name}} [{{post.cityid}}] ({{post.coordlon}}, {{post.coordlat}})
            </a>
            <a href="/del/{{post.id}}">&#10006;</a>
        </li>
        
    {% endfor %}
     <hr>
    <form action="{%url 'importapi:importdataapi' %}" method="POST">
    {% csrf_token %}
    <label>Nazwa miasta:</label>
    <input type="text" id="wpisane_miasto" name="wpisane_miasto">
    <input type="submit" value="Dodaj miasto">
    </form>
    
{% endblock %}

weather/weather_stats/templates/weather_stats/miasto.html
{% extends "weather_stats/base.html" %}

{% block title %}
    Miasto: {{city.name}}
{% endblock %}

{% block body %}
    <div style="float: left;">
    <h1>{{city.name}}</h1>
    Średnia temperatura: {{srednia.temp__avg | floatformat}}&#8451;
    Przeważnie będzie {{popularnosc.0}}
    <br>
    Najcieplej będzie {{srednia.temp__max}}&#8451; {{najcieplejszy.date}}
    
    
    {% for post in weather %}
       <ol>           
           {{post.date}} : {{post.temp}}&#8451;, {{post.weather_desc}} <img src="http://openweathermap.org/img/wn/{{post.weather_icon}}.png" alt="icon">
        </ol>
    {% endfor %}
    </div>
     <style>
        #map {
          width: 400px;
          height: 400px;
          padding:20px;
          background-color: grey;
        }
       </style>
       <div id="map"></div>
       <script>
   // Initialize and add the map
   function initMap() {
     // The location of Uluru
     var uluru = {lat: {{city.coordlat}}, lng: {{city.coordlon}}};
     // The map, centered at Uluru
     var map = new google.maps.Map(
         document.getElementById('map'), {zoom: 4, center: uluru});
     // The marker, positioned at Uluru
     var marker = new google.maps.Marker({position: uluru, map: map});
   }
       </script>
       <script async defer
       src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBK0UaZK51LaNzFXaf1u_6rfqVWFGiR_lE&callback=initMap">
       </script>  
    </div>
{% endblock %}